apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmks-victoria-metrics-operator
  namespace: vm
spec:
  template:
    spec:
      containers:
        - name: operator
          image: victoriametrics/operator:v0.68.0-rc1
          imagePullPolicy: Always
