apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributedCluster
metadata:
  name: vmd
  namespace: vmdistributed
spec:
  vmagent:
    name: global-write-vmagent
    spec:
      replicaCount: 1
  vmauth:
    name: global-read-vmauth
    spec:
      replicaCount: 1
  zones:
    globalOverrideSpec:
      replicationFactor: 1
      clusterVersion: v1.131.0-cluster
      vminsert:
        replicaCount: 2
      vmselect:
        replicaCount: 2
      vmstorage:
        replicaCount: 2
    vmclusters:
    - name: az-a
      spec:
        vminsert:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-a
        vmselect:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-a
        vmstorage:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-a
    - name: az-b
      spec:
        vminsert:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-b
        vmselect:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-b
        vmstorage:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-b
    - name: az-c
      spec:
        vminsert:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-c
        vmselect:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-c
        vmstorage:
          nodeSelector:
            topology.kubernetes.io/zone: europe-central2-c
