apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: vmd
  namespace: vmdistributed
spec:
  vmauth:
    name: global-read-vmauth
    spec:
      replicaCount: 1
  zones:
    - name: az-a
      vmagent:
        name: vmagent-az-a
        spec:
          replicaCount: 1
      vmcluster:
        name: az-a
        spec:
          replicationFactor: 1
          clusterVersion: v1.135.0-cluster
          vminsert:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-a
          vmselect:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-a
          vmstorage:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-a
    - name: az-b
      vmagent:
        name: vmagent-az-b
        spec:
          replicaCount: 1
      vmcluster:
        name: az-b
        spec:
          replicationFactor: 1
          clusterVersion: v1.135.0-cluster
          vminsert:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-b
          vmselect:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-b
          vmstorage:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-b
    - name: az-c
      vmagent:
        name: vmagent-az-c
        spec:
          replicaCount: 1
      vmcluster:
        name: az-c
        spec:
          replicationFactor: 1
          clusterVersion: v1.135.0-cluster
          vminsert:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-c
          vmselect:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-c
          vmstorage:
            replicaCount: 2
            nodeSelector:
              topology.kubernetes.io/zone: europe-central2-c
