apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributedCluster
metadata:
  name: vmd
  namespace: vm-distributed-chart
spec:
  vmagent:
    name: global-write-vmagent
  vmauth:
    name: vmauth-global-read-vmd-vm-distributed
  zones:
    vmclusters:
    - name: central
      ref:
        name: vmcluster-central
    - name: east
      ref:
        name: vmcluster-east
    - name: west
      ref:
        name: vmcluster-west
