apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: vmd
  namespace: vm-distributed-chart
spec:
  vmauth:
    name: vmauth-global-read-vmd-vm-distributed
  zones:
    - name: central
      vmcluster:
        name: vmcluster-central
        spec:
          vminsert:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
    - name: east
      vmcluster:
        name: vmcluster-east
        spec:
          vminsert:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
    - name: west
      vmcluster:
        name: vmcluster-west
        spec:
          vminsert:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
